### ISSUE TITLE
Work with CSS Modules

### ISSUE THREAD

**Issue by itayganor** [rsuite/webpack-multiple-themes-compile#12]
Hi :)

Is there any way to configure this plugin to work with CSS Modules enabled?

(I'm using less, if it matters)

Thanks!

**Comment by hiyangguo** [comment]
I think it is work fine.  You may need [style-loader](https://webpack.docschina.org/loaders/style-loader/) .
You can change loaders by edit `styleLoaders` field like this :
```
styleLoaders: [{ loader: 'style-loader' }, { loader: 'css-loader' }, { loader: 'less-loader' }]
```
And you should install it at the first
```
npm install --save-dev style-loader
```
