### ISSUE TITLE
extract-text-webpack-plugin DEPRECATED

### ISSUE THREAD

**Issue by blueyestar** [rsuite/webpack-multiple-themes-compile#3]
extract-text-webpack-plugin deprecated
 
Please use https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by hiyangguo** [comment]
@blueyestar Mini-css-extract-plugin is difference from extract-text-webpack-plugin , so I need some time to consider how to compatibility with it. Than you for your advice very much.

**Comment by hiyangguo** [comment]
@blueyestar You can use `webpack-multiple-themes-compile@beta` to resolve this issue.
```
npm i webpack-multiple-themes-compile@beta
```
I will publish release at later.
