### ISSUE TITLE
编译时候为什么报这样的错误

### ISSUE THREAD

**Issue by liulinaxue** [rsuite/webpack-multiple-themes-compile#4]
ERROR in (webpack)-multiple-themes-compile/lib/src/less/themes/red.less
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

exports = module.exports = require("../../../../../css-loader/dist/runtime/api.js")(false);
      ^
Unrecognised input

**Comment by hiyangguo** [comment]
@liulinaxue 你这个感觉是 css-loader 的问题
